repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pdm-project/pdm
    rev: 2.15.4
    hooks:
    -   id: pdm-lock-check
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: local
    hooks:
    -   id: no-underscore-prefixed-names
        name: no underscore-prefixed names
        entry: python3 scripts/check_naming.py
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        args: ["--rcfile=.pylintrc"]
        entry: pylint backend/app
        language: system
        types: [python]
