/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Summarise one or more medical documents in a single request, storing nothing.
         *
         *     The documents are read, analysed and answered in memory. No file id is
         *     issued because there is nothing to come back for, and nothing to delete
         *     later. The document text is not echoed back: the summary is the product,
         *     and returning the text would widen what leaves the server for no gain.
         *
         *     A batch holding one document that cannot be read still answers 200, with
         *     that document marked unread and the summary built from the rest. Only a
         *     batch where nothing could be read is refused.
         *
         *     Args:
         *         files: The uploaded documents (PDF, DOCX, TXT)
         *
         *     Returns:
         *         AnalysisResponse: The merged summary and the entities behind it
         *
         *     Raises:
         *         HTTPException: 400 for an invalid file or a batch nothing could be read
         *             from, 413 for a file or batch that is too large, 500 for server
         *             errors
         */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a stored document before its retention window expires.
         *
         *     Args:
         *         file_id: The unique identifier of the document to delete
         *         text_repository: Injected text repository dependency
         *
         *     Raises:
         *         HTTPException: 400 for a malformed file ID, 404 if nothing was stored
         */
        delete: operations["delete_document_api_documents__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_extracted_text/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Extracted Text
         * @description Endpoint to retrieve the entities extracted from a processed file.
         *
         *     Entities are extracted at upload time, so this only reads what was stored.
         *     The document text comes back only when the deployment kept it.
         *
         *     Args:
         *         file_id: The unique identifier of the file to read
         *         text_repository: Injected text repository dependency
         *         entity_extractor: Injected entity extractor dependency
         *
         *     Returns:
         *         ExtractionResponse: Contains the file ID, identified medical entities and,
         *         when retained, the extracted text
         *
         *     Raises:
         *         HTTPException: 404 if file not found or not processed yet
         */
        get: operations["get_extracted_text_api_get_extracted_text__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload_document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a medical document for text extraction and entity recognition.
         *
         *     Args:
         *         file: The uploaded file (PDF, DOCX, TXT)
         *
         *     Returns:
         *         UploadResponse: Contains file ID, filename, and upload confirmation
         *
         *     Raises:
         *         HTTPException: 400 for invalid file type, 500 for server errors
         */
        post: operations["upload_document_api_upload_document__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload_documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Documents
         * @description Upload multiple medical documents for text extraction and entity recognition.
         *
         *     Each file is processed on its own and answered with its own id. The batch id
         *     only correlates the files of this request: nothing is written under it, so
         *     there is one less patient-adjacent key living out a retention window.
         *
         *     Args:
         *         files: The uploaded files (PDF, DOCX, TXT)
         *
         *     Returns:
         *         MultipleUploadResponse: Contains batch id with associated file ids
         *
         *     Raises:
         *         HTTPException: 400 for invalid file type, 500 for server errors
         */
        post: operations["upload_documents_api_upload_documents__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness: the process is up and the event loop is answering.
         *
         *     This says nothing about the model. Uvicorn opens its sockets only once the
         *     lifespan handler returns, so a served answer here already implies the load
         *     has finished one way or the other - use `/readyz` for which way.
         */
        get: operations["health_check_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness: the model is loaded, so an analysis will not wait for weights.
         *
         *     Refuses with the same envelope and the same message as the routes that need
         *     the model, so a caller reads one answer rather than two. The body carries a
         *     fixed string - no path, no configuration, no reason.
         */
        get: operations["readiness_check_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description Result of a stateless analysis. Nothing behind this response is stored.
         */
        AnalysisResponse: {
            /**
             * Documents
             * @description Every submitted document, in submission order: the entities found in it for a caller that needs more than the summary, and whether it could be read at all. A document with `read` false is not behind the summary - the batch is refused outright only when none of them could be read.
             */
            documents: components["schemas"]["AnalyzedDocument"][];
            /**
             * Mapping Info
             * @description Information about the label mapping used (language, dataset)
             */
            mapping_info?: {
                [key: string]: string;
            } | null;
            /**
             * Retained
             * @description Always false: this endpoint never writes to storage
             * @default false
             */
            retained: boolean;
            /** @description The submitted documents merged into one readable patient summary. This is what the endpoint is for; the rest is detail behind it. */
            summary: components["schemas"]["ClinicalSummary"];
        };
        /**
         * AnalyzedDocument
         * @description One submitted document: its entities, and whether it was read at all.
         *
         *     Callers that already read `documents[i]` as entities keep working - the
         *     entity categories are unchanged, and an unread document simply has none.
         *     The document is identified by its position in the list, which is the
         *     caller's own submission order, so no filename has to cross the boundary for
         *     the caller to say which of its files was skipped.
         */
        AnalyzedDocument: {
            /**
             * Anatomy
             * @description Anatomical structures
             * @default []
             */
            anatomy: components["schemas"]["EntityDetail"][];
            /**
             * Examinations
             * @description Medical examinations
             * @default []
             */
            examinations: components["schemas"]["EntityDetail"][];
            /**
             * Measurements
             * @description Measurements and values
             * @default []
             */
            measurements: components["schemas"]["EntityDetail"][];
            /**
             * Other
             * @description Other medical entities
             * @default []
             */
            other: components["schemas"]["EntityDetail"][];
            /**
             * Pathologies
             * @description Diseases and conditions
             * @default []
             */
            pathologies: components["schemas"]["EntityDetail"][];
            /**
             * Patient Info
             * @description Patient demographic information
             * @default []
             */
            patient_info: components["schemas"]["EntityDetail"][];
            /**
             * Read
             * @description False when no text could be read from this document. It is then not behind the summary, and its entity categories are empty.
             */
            read: boolean;
            /**
             * Symptoms
             * @description Signs and symptoms
             * @default []
             */
            symptoms: components["schemas"]["EntityDetail"][];
            /**
             * Temporal
             * @description Temporal information
             * @default []
             */
            temporal: components["schemas"]["EntityDetail"][];
            /**
             * Treatments
             * @description Treatments and medications
             * @default []
             */
            treatments: components["schemas"]["EntityDetail"][];
            /** @description Why the document could not be read. Null when it was read. */
            unreadable_reason: components["schemas"]["UnreadableReason"] | null;
        };
        /** Body_analyze_api_analyze_post */
        Body_analyze_api_analyze_post: {
            /**
             * Files
             * @description The documents to summarise (PDF, DOCX, TXT). Several documents are taken to be about the same patient and merged into one summary.
             */
            files: string[];
        };
        /** Body_upload_document_api_upload_document__post */
        Body_upload_document_api_upload_document__post: {
            /**
             * File
             * @description The file to upload (PDF, DOCX, TXT).
             */
            file: string;
        };
        /** Body_upload_documents_api_upload_documents__post */
        Body_upload_documents_api_upload_documents__post: {
            /**
             * Files
             * @description List of medical documents to upload. Supported formats: PDF, DOCX, TXT. Maximum size: 10MB per file.
             */
            files: string[];
        };
        /**
         * ClinicalSummary
         * @description A readable summary of one or more documents about the same patient.
         *
         *     Everything here is assembled from what the NER model emitted. No wording is
         *     generated: each finding is a span the model marked, deduplicated across the
         *     submitted documents and placed under a fixed heading.
         */
        ClinicalSummary: {
            /**
             * Document Count
             * @description How many documents were read to build this summary. Lower than the number submitted when a document could not be read: see `AnalysisResponse.documents[].read`.
             */
            document_count: number;
            /**
             * Empty
             * @description True when nothing clinical was found. The caller should say so rather than render an empty page.
             * @default false
             */
            empty: boolean;
            /**
             * Patient
             * @description The demographic line, e.g. 'Patient, 67 ans, homme.' Absent when the documents carry no demographic mention.
             */
            patient?: string | null;
            /**
             * Sections
             * @description Clinical sections, in reading order. Empty ones are omitted.
             * @default []
             */
            sections: components["schemas"]["SummarySection"][];
        };
        /**
         * EntityDetail
         * @description Detailed information about an extracted entity.
         */
        EntityDetail: {
            /**
             * End
             * @description End position in the text. Absent when the document text was not retained, since an offset means nothing without the text.
             */
            end?: number | null;
            /**
             * Label
             * @description The entity label/type from the NER model
             */
            label: string;
            /**
             * Score
             * @description Confidence score (0-1)
             */
            score: number;
            /**
             * Start
             * @description Start position in the text. Absent when the document text was not retained, since an offset means nothing without the text.
             */
            start?: number | null;
            /**
             * Text
             * @description The extracted entity text
             */
            text: string;
        };
        /**
         * ErrorDetail
         * @description The body of a refusal.
         *
         *     Routes raise HTTPException with a fixed message, and add context only when
         *     the context is about the request rather than the document: the allowed file
         *     types, a size limit, a batch cap. Nothing here quotes document content.
         */
        ErrorDetail: {
            /**
             * Allowed Extensions
             * @description File extensions this endpoint accepts
             */
            allowed_extensions?: string[] | null;
            /**
             * Allowed Types
             * @description File types this endpoint accepts
             */
            allowed_types?: string[] | null;
            /**
             * Max Files
             * @description Largest accepted number of files in one batch
             */
            max_files?: number | null;
            /**
             * Max Size Bytes
             * @description Largest accepted file, in bytes
             */
            max_size_bytes?: number | null;
            /**
             * Message
             * @description Content-free description of the failure
             */
            message: string;
            /**
             * Received Size Bytes
             * @description Size of the rejected file, in bytes
             */
            received_size_bytes?: number | null;
            /**
             * Received Type
             * @description The rejected content type, as the client declared it
             */
            received_type?: string | null;
        };
        /**
         * ErrorResponse
         * @description How every refusal reaches the client.
         *
         *     FastAPI wraps a raised HTTPException as {"detail": ...}, so this is the
         *     shape the frontend actually parses. Documenting the inner payload alone
         *     described a body the API never sends.
         */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /**
         * ExtractedEntities
         * @description All extracted medical entities grouped by category.
         */
        ExtractedEntities: {
            /**
             * Anatomy
             * @description Anatomical structures
             * @default []
             */
            anatomy: components["schemas"]["EntityDetail"][];
            /**
             * Examinations
             * @description Medical examinations
             * @default []
             */
            examinations: components["schemas"]["EntityDetail"][];
            /**
             * Measurements
             * @description Measurements and values
             * @default []
             */
            measurements: components["schemas"]["EntityDetail"][];
            /**
             * Other
             * @description Other medical entities
             * @default []
             */
            other: components["schemas"]["EntityDetail"][];
            /**
             * Pathologies
             * @description Diseases and conditions
             * @default []
             */
            pathologies: components["schemas"]["EntityDetail"][];
            /**
             * Patient Info
             * @description Patient demographic information
             * @default []
             */
            patient_info: components["schemas"]["EntityDetail"][];
            /**
             * Symptoms
             * @description Signs and symptoms
             * @default []
             */
            symptoms: components["schemas"]["EntityDetail"][];
            /**
             * Temporal
             * @description Temporal information
             * @default []
             */
            temporal: components["schemas"]["EntityDetail"][];
            /**
             * Treatments
             * @description Treatments and medications
             * @default []
             */
            treatments: components["schemas"]["EntityDetail"][];
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /**
             * Expires In Seconds
             * @description Seconds before the stored document is automatically deleted
             */
            expires_in_seconds?: number | null;
            /** @description Medical entities found in the text with detailed information */
            extracted_entities: components["schemas"]["ExtractedEntities"];
            /**
             * File Id
             * @description Unique identifier of the processed file
             */
            file_id: string;
            /**
             * Mapping Info
             * @description Information about the label mapping used (language, dataset)
             */
            mapping_info?: {
                [key: string]: string;
            } | null;
            /**
             * Processed At
             * @description When the extraction was completed
             */
            processed_at?: string | null;
            /**
             * Text
             * @description Extracted text from the document. Null unless the deployment opted into storing document text.
             */
            text?: string | null;
        };
        /**
         * Finding
         * @description One deduplicated finding, and which documents it came from.
         */
        Finding: {
            /**
             * Documents
             * @description Indices into the submitted batch, ascending, of every document this finding was found in. They index the request's own file order - and `AnalysisResponse.documents` - so a caller can name the source from what it submitted, without this path ever having to echo a filename.
             */
            documents: number[];
            /**
             * Text
             * @description The span the model marked, as it is reported
             */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MultipleUploadResponse */
        MultipleUploadResponse: {
            /**
             * Batch Id
             * @description Identifier correlating the files of one upload request. Nothing is stored under it: the batch cannot be resolved server-side, only the file IDs can.
             */
            batch_id: string;
            /**
             * File Ids
             * @description List of file IDs in the batch
             */
            file_ids: string[];
            /**
             * Message
             * @description Batch upload status message
             */
            message: string;
            /**
             * Total Files
             * @description Total number of files processed
             */
            total_files?: number | null;
            /**
             * Uploaded At
             * @description Upload timestamp
             */
            uploaded_at?: string | null;
        };
        /**
         * SummarySection
         * @description One clinical axis of the summary, as a heading and its findings.
         */
        SummarySection: {
            /**
             * Findings
             * @description The same findings as a list, most-supported first, for a caller that would rather lay them out itself
             */
            findings: components["schemas"]["Finding"][];
            /**
             * Heading
             * @description Human-readable heading for the section
             */
            heading: string;
            /**
             * Key
             * @description Stable category key, e.g. 'pathologies'
             */
            key: string;
            /**
             * Sentence
             * @description The section's findings as one sentence, ready to read
             */
            sentence: string;
        };
        /**
         * UnreadableReason
         * @description Why a submitted document is not behind the summary.
         *
         *     Closed on purpose, and content-free: a caller renders the position it
         *     submitted, never a filename or a parser message. More members may be added
         *     as more ways to fail are told apart; today every failure a document can
         *     cause on this path is "nothing could be read from it".
         * @enum {string}
         */
        UnreadableReason: "no_text";
        /** UploadResponse */
        UploadResponse: {
            /**
             * Content Type
             * @description MIME type of the file
             */
            content_type?: string | null;
            /**
             * Expires In Seconds
             * @description Seconds before the stored document is automatically deleted
             */
            expires_in_seconds?: number | null;
            /**
             * File Id
             * @description Unique identifier of the uploaded file
             */
            file_id: string;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * Message
             * @description Upload status message
             */
            message: string;
            /**
             * Size
             * @description File size in bytes
             */
            size?: number | null;
            /**
             * Uploaded At
             * @description Upload timestamp
             */
            uploaded_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Invalid or unreadable document */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A file is too large, or the batch holds too many files */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The model is not loaded yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_document_api_documents__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the document to delete */
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid file ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extracted_text_api_get_extracted_text__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the uploaded file to read entities from */
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Invalid file ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File not found or not processed yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The model is not loaded yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_api_upload_document__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_upload_document__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Invalid file type, or a document that cannot be read */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The model is not loaded yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_documents_api_upload_documents__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_upload_documents__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipleUploadResponse"];
                };
            };
            /** @description Invalid file type, or a document that cannot be read */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A file is too large, or the batch holds too many files */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The model is not loaded yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description The model is not loaded yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
