import { readFileSync } from 'node:fs'
import path from 'node:path'

import openapiTS, { astToString } from 'openapi-typescript'
import { describe, expect, it } from 'vitest'

// vitest runs from the frontend root, which is also where `npm run
// generate:types` resolves its paths from.
const SCHEMA = path.resolve(process.cwd(), '../backend/openapi.json')
const GENERATED = path.resolve(process.cwd(), 'app/types/api.ts')

// The CLI writes this banner above what the generator returns.
const BANNER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`

describe('app/types/api.ts', () => {
  // The backend test catches its own schema drifting from the app. This one
  // closes the other half: a checked-in schema whose types were never
  // regenerated leaves the components typed against yesterday's API, which is
  // the exact failure the generated types exist to prevent.
  it('is what the backend schema generates', async () => {
    const schema = JSON.parse(readFileSync(SCHEMA, 'utf8'))

    const generated = astToString(await openapiTS(schema))
    const committed = readFileSync(GENERATED, 'utf8')

    expect(committed.startsWith(BANNER)).toBe(true)
    expect(committed.slice(BANNER.length)).toBe(generated)
  }, 30_000)
})
